INSERT INTO
    customers (name)
VALUES
    ('Abebe Kebede'),
    ('Almaz Getachew'),
    ('Bereket Tesfaye'),
    ('Dawit Abebe'),
    ('Tigist Assefa'),
    ('Kebede Bekele'),
    ('Selamawit Demissie'),
    ('Tewodros Fikru'),
    ('Mekdes Girma'),
    ('Betelhem Haile'),
    ('Solomon Alemu'),
    ('Tigist Alemayehu'),
    ('Amanuel Berhanu'),
    ('Kidist Dessalegn'),
    ('Mulugeta Asrat'),
    ('Mahlet Fikadu'),
    ('Tesfaye Hagos'),
    ('Yared Habte'),
    ('Yordanos Kassahun'),
    ('Mariam Legesse'),
    ('Getu Mekonnen'),
    ('Betelhem Nigussie'),
    ('Samrawit Sisay'),
    ('Eyob Tilahun'),
    ('Hanna Yilma'),
    ('Bereket Worku'),
    ('Meron Abate'),
    ('Tewabech Eshetu'),
    ('Fitsum Gizaw'),
    ('Marta Kidane'),
    ('Abel Mengistu'),
    ('Birtukan Nega'),
    ('Mekonnen Seyoum'),
    ('Rahel Tefera'),
    ('Sisay Workneh'),
    ('Eleni Yohannes'),
    ('Temesgen Zewdie'),
    ('Zebiba Ahmed'),
    ('Haile Fekadu'),
    ('Selam Feleke'),
    ('Desta Girmachew'),
    ('Meselech Kassaye'),
    ('Kassahun Bekele'),
    ('Hirut Asrat'),
    ('Tsegaye Belay'),
    ('Rediet Damtew'),
    ('Aschalew Esayas'),
    ('Getnet Fufa'),
    ('Wondimu Goshu'),
    ('Mulu Habtamu');

INSERT INTO
    address (customer_id, address)
VALUES
    (1, 'Bole, Addis Ababa'),
    (2, 'Kazanchis, Addis Ababa'),
    (3, 'Megenagna, Addis Ababa'),
    (4, 'Arat Kilo, Addis Ababa'),
    (5, 'Piazza, Addis Ababa'),
    (6, 'Kirkos, Addis Ababa'),
    (7, 'Mexico, Addis Ababa'),
    (8, 'Sar Bet, Addis Ababa'),
    (9, 'Gergi, Addis Ababa'),
    (10, 'Lafto, Addis Ababa'),
    (11, 'Lebuw, Addis Ababa'),
    (12, 'Gofa, Addis Ababa'),
    (13, 'Ayat, Addis Ababa'),
    (14, 'Gotera, Addis Ababa'),
    (15, 'Nifas Silk, Addis Ababa'),
    (16, 'Cazanchise, Addis Ababa'),
    (17, 'Saris, Addis Ababa'),
    (18, 'Kality, Addis Ababa'),
    (19, 'Mebrat Hail, Addis Ababa'),
    (20, 'Adwa, Tigray'),
    (21, 'Hawassa, Sidama'),
    (22, 'Dire Dawa, Dire Dawa'),
    (23, 'Bahir Dar, Amhara'),
    (24, 'Gondar, Amhara'),
    (25, 'Mekelle, Tigray'),
    (26, 'Jimma, Oromia'),
    (27, 'Jinka, SNNPR'),
    (28, 'Harar, Harari'),
    (29, 'Assosa, Benishangul-Gumuz'),
    (30, 'Gambella, Gambella'),
    (31, 'Dessie, Amhara'),
    (32, 'Debre Birhan, Amhara'),
    (33, 'Adama, Oromia'),
    (34, 'Bishoftu, Oromia'),
    (35, 'Shashemene, Oromia'),
    (36, 'Ziway, Oromia'),
    (37, 'Woliso, Oromia'),
    (38, 'Dilla, SNNPR'),
    (39, 'Wolaita Sodo, SNNPR'),
    (40, 'Arba Minch, SNNPR'),
    (41, 'Asella, Oromia'),
    (42, 'Ambo, Oromia'),
    (43, 'Nekemte, Oromia'),
    (44, 'Goba, Oromia'),
    (45, 'Hosaena, SNNPR'),
    (46, 'Hosanna, SNNPR'),
    (47, 'Debre Markos, Amhara'),
    (48, 'Debre Tabor, Amhara'),
    (49, 'Bale Robe, Oromia'),
    (50, 'Assela, Oromia');

INSERT INTO
    company (customer_id, company)
VALUES
    (1, 'EthioTelecom'),
    (2, 'EthioAirlines'),
    (3, 'Dashen Bank'),
    (4, 'Awash Bank'),
    (5, 'Berhan Bank'),
    (6, 'Nib Bank'),
    (7, 'Abyssinia Bank'),
    (8, 'Commercial Bank of Ethiopia'),
    (9, 'Zemen Bank'),
    (10, 'Wegagen Bank'),
    (11, 'Enat Bank'),
    (12, 'Lion Insurance'),
    (13, 'Nyala Insurance'),
    (14, 'Oromia Insurance'),
    (15, 'United Insurance'),
    (16, 'Abay Insurance'),
    (17, 'Global Insurance'),
    (18, 'Tsehay Insurance'),
    (19, 'Anbessa Shoe'),
    (20, 'Ethiopian Sugar Corporation'),
    (21, 'Ethio Cement'),
    (22, 'Dangote Cement'),
    (23, 'Habesha Cement'),
    (24, 'Derba Cement'),
    (25, 'Mugher Cement'),
    (26, 'Mesfin Industrial Engineering'),
    (27, 'Horizon Addis Tyre'),
    (28, 'East Africa Bottling'),
    (29, 'Ambo Mineral Water'),
    (30, 'Addis Pharmaceuticals'),
    (31, 'Cadila Pharmaceuticals'),
    (32, 'Sun Pharma'),
    (33, 'GlaxoSmithKline'),
    (34, 'BGI Ethiopia'),
    (35, 'Meta Abo Brewery'),
    (36, 'Dashen Brewery'),
    (37, 'Harar Brewery'),
    (38, 'Habesha Brewery'),
    (39, 'Bunna International Bank'),
    (40, 'Cooperative Bank of Oromia'),
    (41, 'Debub Global Bank'),
    (42, 'Addis Ababa Housing Project'),
    (43, 'Sunshine Construction'),
    (44, 'Sur Construction'),
    (45, 'Flintstone Engineering'),
    (46, 'Beza Consulting Engineers'),
    (47, 'Yotek Construction'),
    (48, 'CRBC Ethiopia'),
    (49, 'CCC Ethiopia'),
    (
        50,
        'China Civil Engineering Construction Corporation'
    );